In [6]:
import numpy as np
# 1. Input:
arr = np.array([[[1, 2, 3],
                   [4, 5, 6], [7, 8, 9]],
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                     [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
#    Extract the first layer (all rows and columns from the first 2D slice).
arr
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# 2. Input:
arr = np.array([[[5, 6, 7], [8, 9, 10], [11, 12, 13]],
                     [[15, 16, 17], [18, 19, 20], [21, 22, 23]],
                     [[25, 26, 27], [28, 29, 30], [31, 32, 33]]])
  #  Extract the element 26 from the array.
arr
arr[2,0,1]

26

In [12]:
# 3 input
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                     [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
# Extract all rows and the last column of the second layer.
print(arr)
arr[1,::,2]


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([12, 15, 18])

In [15]:
# 4. Input:
arr = np.array([[[2, 4, 6], [8, 10, 12], [14, 16, 18]],
                     [[20, 22, 24], [26, 28, 30], [32, 34, 36]],
                     [[38, 40, 42], [44, 46, 48], [50, 52, 54]]])
# Extract the last two layers (all rows and columns from the last two 2D slices).
print(arr)
print()
arr[1:]

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]



array([[[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]],

       [[38, 40, 42],
        [44, 46, 48],
        [50, 52, 54]]])

In [17]:
# 5. Input:
arr = np.array([[[1, 1, 1], [2, 2, 2], [3, 3, 3]],
                     [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
                     [[7, 7, 7], [8, 8, 8], [9, 9, 9]]])
# Extract the first two rows and first two columns of the last layer.
print(arr)
arr[2,:2,:2]

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]

 [[7 7 7]
  [8 8 8]
  [9 9 9]]]


array([[7, 7],
       [8, 8]])

In [19]:
# 6. Input:
arr = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
                     [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
                     [[18, 19, 20], [21, 22, 23], [24, 25, 26]]])
# Extract the second column from all layers.
print(arr)
arr[:,:,1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [21]:
# 7. Input:
arr = np.array([[[10, 20, 30], [40, 50, 60], [70, 80, 90]],
                     [[15, 25, 35], [45, 55, 65], [75, 85, 95]],
                     [[100, 200, 300], [400, 500, 600], [700, 800, 900]]])
# Extract all elements from the second row across all layers.
print(arr)
arr[:,1,:]

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[ 15  25  35]
  [ 45  55  65]
  [ 75  85  95]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


array([[ 40,  50,  60],
       [ 45,  55,  65],
       [400, 500, 600]])

In [26]:
# 8. Input:
arr= np.array([[[3, 6, 9], [12, 15, 18], [21, 24, 27]],
                     [[30, 33, 36], [39, 42, 45], [48, 51, 54]],
                     [[57, 60, 63], [66, 69, 72], [75, 78, 81]]])
#  Extract a 2x2x2 sub-array starting from the top-left corner of the array.
print(arr)
print("Output")
arr[:2,:2,:2]

[[[ 3  6  9]
  [12 15 18]
  [21 24 27]]

 [[30 33 36]
  [39 42 45]
  [48 51 54]]

 [[57 60 63]
  [66 69 72]
  [75 78 81]]]
Output


array([[[ 3,  6],
        [12, 15]],

       [[30, 33],
        [39, 42]]])

In [28]:
# 9. Input:
arr= np.array([[[5, 10, 15], [20, 25, 30], [35, 40, 45]],
                     [[50, 55, 60], [65, 70, 75], [80, 85, 90]],
                     [[95, 100, 105], [110, 115, 120], [125, 130, 135]]])
# Extract the last two elements of the third row from the second layer.
print(arr)
print("Output")
print(arr[1,2,1:])

[[[  5  10  15]
  [ 20  25  30]
  [ 35  40  45]]

 [[ 50  55  60]
  [ 65  70  75]
  [ 80  85  90]]

 [[ 95 100 105]
  [110 115 120]
  [125 130 135]]]
Output
[85 90]


In [30]:
# 10. Input:
arr = np.array([[[2, 4, 6], [8, 10, 12], [14, 16, 18]],
                      [[20, 22, 24], [26, 28, 30], [32, 34, 36]],
                      [[38, 40, 42], [44, 46, 48], [50, 52, 54]]])
# Extract the first column of every row from the second layer.
print(arr)
print("output")
print(arr[1,:,0])

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]
output
[20 26 32]


In [32]:
# 11. Input:
arr = np.array([[[1, 1, 1], [2, 2, 2], [3, 3, 3]],
                      [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
                      [[7, 7, 7], [8, 8, 8], [9, 9, 9]]])
    # Extract all rows except the last one from all layers.
print(arr)
print("output")
print(arr[:,:2,:])

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]

 [[7 7 7]
  [8 8 8]
  [9 9 9]]]
output
[[[1 1 1]
  [2 2 2]]

 [[4 4 4]
  [5 5 5]]

 [[7 7 7]
  [8 8 8]]]


In [34]:
# 12. Input:
arr = np.array([[[0, 2, 4], [6, 8, 10], [12, 14, 16]],
                      [[18, 20, 22], [24, 26, 28], [30, 32, 34]],
                      [[36, 38, 40], [42, 44, 46], [48, 50, 52]]])
    # Extract all elements except the first two columns from the last layer.
print(arr)
print("Output")
print(arr[2,:,2])

[[[ 0  2  4]
  [ 6  8 10]
  [12 14 16]]

 [[18 20 22]
  [24 26 28]
  [30 32 34]]

 [[36 38 40]
  [42 44 46]
  [48 50 52]]]
Output
[40 46 52]


In [37]:
# 13. Input:
arr = np.array([[[100, 200, 300], [400, 500, 600], [700, 800, 900]],
                      [[110, 210, 310], [410, 510, 610], [710, 810, 910]],
                      [[120, 220, 320], [420, 520, 620], [720, 820, 920]]])
    # Extract the elements at positions (1, 1, 1) and (2, 2, 2).
print(arr[1,1,1])
print(arr[2,2,2])

510
920


In [40]:
# 14. Input:
arr= np.array([[[10, 20, 30], [40, 50, 60], [70, 80, 90]],
                      [[15, 25, 35], [45, 55, 65], [75, 85, 95]],
                      [[100, 200, 300], [400, 500, 600], [700, 800, 900]]])
    # Extract a 2x2x2 sub-array starting from the middle of the array.
print(arr)
print("output")
print(arr[1:,1:,1:])
na=arr[1]



[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[ 15  25  35]
  [ 45  55  65]
  [ 75  85  95]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]
output
[[[ 55  65]
  [ 85  95]]

 [[500 600]
  [800 900]]]


In [44]:
# 15. Input:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                      [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                      [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
    # Extract all layers but reverse the row order of the second layer.
print(arr)
print("Output")
na=arr[:]
na[1]=arr[1,:,::-1]
print(na)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Output
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[12 11 10]
  [15 14 13]
  [18 17 16]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [41]:
# prompt: # Extract all layers but reverse the row order of the second layer.

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                      [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                      [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

# Extract all layers
new_arr = arr[:]

# Reverse the row order of the second layer
new_arr[1] = np.flip(arr[1], axis=0)

new_arr