In [2]:
# 1. Create a 2D numpy array of shape (3, 3) with random integers. Append a new row [10, 20, 30] to the array and print the result.
import numpy as np


In [9]:
arr=np.array([[4,5,6],
              [11,20,23],
              [14,45,68]])
arr=np.append(arr,[[10,20,30]],axis=0)
arr

array([[ 4,  5,  6],
       [11, 20, 23],
       [14, 45, 68],
       [10, 20, 30]])

In [21]:
# 2. Given a 2D numpy array of shape (2, 2), insert a new column [5, 10] at the second position and print the modified array.
arr=np.array([[1,2],[3,4]])
arr
arr=np.append(arr,[[5],[10]],axis=1)
arr

array([[ 1,  2,  5],
       [ 3,  4, 10]])

In [25]:
# 3. Create a 3D numpy array of shape (2, 2, 2) with random integers. Append a new 2D array of shape (1, 2, 2) with values [[[7, 8], [9, 10]]] and print the result.
arr=np.array([[[1,2],
               [3,4]],
              [[6,5],
               [8,7]]
              ])
arr
arr=np.append(arr,[[[7,8],[9,10]]],axis=0)
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 6,  5],
        [ 8,  7]],

       [[ 7,  8],
        [ 9, 10]]])

In [28]:
# 4. Given a 2D numpy array of shape (4, 3), insert a new row [1, 2, 3] at the third position and print the modified array.
arr=np.array([[4,5,6],
              [11,20,23],
              [14,45,68],
              [3,8,9]])
arr
np.insert(arr,3,[1,2,3],axis=0)

array([[ 4,  5,  6],
       [11, 20, 23],
       [14, 45, 68],
       [ 1,  2,  3],
       [ 3,  8,  9]])

In [30]:
# 5. Create a 2D numpy array of shape (2, 4) with random integers. Append a new column [6, 7] at the end and print the result.
arr=np.array([[4,5,6,0],
              [11,20,23,8]])
arr
np.append(arr,[ [6],[7]],axis=1)

array([[ 4,  5,  6,  0,  6],
       [11, 20, 23,  8,  7]])

In [33]:
# 6. Given a 3D numpy array of shape (3, 3, 3), insert a new 2D array of shape (1, 3, 3)
# with values [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]] at the second position and print the modified array.
arr=np.array([[[1,50,21],
               [32,50,34],
               [1,1,1]],

              [[1,50,21],
               [32,30,34],
                [1,1,1]],

              [[100,50,201],
               [321,0,340],
              [1,1,1]
              ]])
print(arr)
np.insert(arr,2,[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]],axis=0)


[[[  1  50  21]
  [ 32  50  34]
  [  1   1   1]]

 [[  1  50  21]
  [ 32  30  34]
  [  1   1   1]]

 [[100  50 201]
  [321   0 340]
  [  1   1   1]]]


array([[[  1,  50,  21],
        [ 32,  50,  34],
        [  1,   1,   1]],

       [[  1,  50,  21],
        [ 32,  30,  34],
        [  1,   1,   1]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[100,  50, 201],
        [321,   0, 340],
        [  1,   1,   1]]])

In [35]:
# 7. Create a 2D numpy array of shape (5, 2) with random integers. Insert a new row [11, 12] at the beginning and print the modified array.
arr=np.array([[1,2],
               [3,4],
              [6,5],
               [8,7],
              [10,22]])
print(arr)
np.insert(arr,0,[[11,12]],axis=0)

[[ 1  2]
 [ 3  4]
 [ 6  5]
 [ 8  7]
 [10 22]]


array([[11, 12],
       [ 1,  2],
       [ 3,  4],
       [ 6,  5],
       [ 8,  7],
       [10, 22]])

In [39]:
# 8. Given a 2D numpy array of shape (3, 5), append a new row [13, 14, 15, 16, 17] and print the result.
arr=np.array([[4,5,   6,1,2],
        [  7,   8,   9,5,6],[100,  50, 201,8,9]])
print(arr)
np.append(arr,[[13,14,15,16,17]],axis=0
)

[[  4   5   6   1   2]
 [  7   8   9   5   6]
 [100  50 201   8   9]]


array([[  4,   5,   6,   1,   2],
       [  7,   8,   9,   5,   6],
       [100,  50, 201,   8,   9],
       [ 13,  14,  15,  16,  17]])

In [56]:
# 9. Create a 3D numpy array of shape (2, 2, 3) with random integers. Insert a new 2D array of shape (1, 2, 3)
#  with values [[[18, 19, 20], [21, 22, 23]]] at the end and print the modified array.
import numpy as np
arr=np.array([
    [
        [1,2,3],
         [4,5,6]
    ],
    [
        [6,7,8],
         [10,11,12]
     ]
])
arr
np.insert(arr,-1,[[18, 19, 20],[21, 22, 23]],axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [10, 11, 12]]])

In [60]:
# 10. Given a 2D numpy array of shape (2, 3), insert a new column [8, 9] at the first position and print the modified array.
arr=np.array([[1,2,3],
               [4,5,6]])
arr
np.insert(arr,0,[8,9],axis=1)

array([[8, 1, 2, 3],
       [9, 4, 5, 6]])

In [61]:
# 11. Create a 2D numpy array of shape (4, 4) with random integers. Append a new row [24, 25, 26, 27] and print the result.
arr=np.array([[1,2,3,8],
               [4,5,6,9],
              [1,2,31,8],
               [4,55,6,9]])
print(arr)
np.append(arr,[[24,25,26,27]])

[[ 1  2  3  8]
 [ 4  5  6  9]
 [ 1  2 31  8]
 [ 4 55  6  9]]


In [67]:
# 12. Given a 3D numpy array of shape (1, 3, 3), insert a new 2D array of shape (1, 3, 3)
# with values [[[28, 29, 30], [31, 32, 33], [34, 35, 36]]] at the beginning and print the modified array.
arr=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]]])
print(arr)
np.insert(arr,0, [[[28, 29, 30], [31, 32, 33], [34, 35, 36]]],axis=0)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [69]:
# 13. Create a 2D numpy array of shape (3, 2) with random integers. Insert a new column [37, 38, 39] at the second position and print the modified array.
arr=np.array([
    [1,2],
    [3,4],
    [5,6]])
arr
np.insert(arr,1,[37,38,39],axis=1)

array([[ 1, 37,  2],
       [ 3, 38,  4],
       [ 5, 39,  6]])

In [70]:
# 14. Given a 2D numpy array of shape (2, 4), append a new column [40, 41] and print the result.
arr=np.array([
    [1,2,3,4],
    [5,6,7,8]])
arr
np.append(arr,[[40],[41]],axis=1)

array([[ 1,  2,  3,  4, 40],
       [ 5,  6,  7,  8, 41]])

In [72]:
# 15. Create a 3D numpy array of shape (2, 2, 2) with random integers. Insert a new 2D array of shape (1, 2, 2)
# with values [[[42, 43], [44, 45]]] at the first position and print the modified array.
arr=np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]]])
arr
np.insert(arr,0,[[[42,43],[44,45]]],axis=0)

array([[[42, 43],
        [44, 45]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]]])