In [1]:
import numpy as np

In [2]:
#  1. The Warehouse Inventory
     
#   You work as a data analyst for a large warehouse that stores products in different sections. The warehouse's inventory is represented as a 2D NumPy array, where each row represents a section, and each column represents the quantity of products in different categories. The warehouse data is stored in the following array:

warehouse = np.array([[100, 200, 150, 180], 
                         [50, 80, 120, 90], 
                         [200, 250, 180, 220], 
                         [60, 90, 75, 100]])
print(warehouse)
#   Task:  
#   - Retrieve the quantities of products from sections 2 and 3 in categories 1 and 2.
print("Task1",warehouse[1:3,:2])
#   - How many products are stored in section 4, categories 2 and 3 combined?
print("Task2",warehouse[3,2:])
#   - Find the total number of products across all categories in section 1.
print("Task3",np.sum(warehouse[0]))

[[100 200 150 180]
 [ 50  80 120  90]
 [200 250 180 220]
 [ 60  90  75 100]]
Task1 [[ 50  80]
 [200 250]]
Task2 [ 75 100]
Task3 630


In [3]:
 # 2. Mountain Range Data     
   # You're analyzing elevation data from a mountain range, stored in a 2D NumPy array where each row represents a different mountain and 
# each column represents the elevation at a different point along the mountain.
elevations = np.array([[500, 1200, 1500, 1600],
                          [700, 1100, 1400, 1800],
                          [450, 950, 1400, 1700],
                          [400, 800, 1300, 1500]])
print(elevations)

#   Task:
#   - Extract the elevation data from the third mountain (row) at the second and third points (columns).
print("Task1",elevations[2,2:4])
#   - What is the highest elevation point across all mountains, and at which point (column) does this occur?
mx=np.max(elevations)
print(np.where(elevations==mx)[0])
#   - Calculate the average elevation for each mountain and return it as a 1D array.
arr=np.array([])
for i in range(len(elevations)):
    arr=np.append(arr,np.sum(elevations[i])/len(elevations[i]))
print(arr)    

[[ 500 1200 1500 1600]
 [ 700 1100 1400 1800]
 [ 450  950 1400 1700]
 [ 400  800 1300 1500]]
Task1 [1400 1700]
[1]
[1200. 1250. 1125. 1000.]


In [4]:
#  3. Sports Performance Analysis     
#   You are tasked with analyzing the performance of athletes in a series of events. The performance data is stored in a 2D NumPy array, where each row represents an athlete and each column represents their score in a different event.
scores = np.array([[12, 15, 10, 17],
                      [14, 13, 12, 18],
                      [10, 11, 9, 14],
                      [16, 17, 18, 19]])
print(scores)
   
#   Task:
#   - Retrieve the scores for the second and third athletes in events 2 and 3.
print("Task1",scores[1:3,1:3])
#   - Which athlete performed the best overall? (Consider the sum of their scores across all events.)
mx=0
athlet=0
for i in range(len(scores)):
    if np.sum(scores[i])>mx:
        mx=np.sum(scores[i])
        athlet=i+1
print("Task2",athlet,mx)
#   - Calculate the average score for each event (i.e., across all athletes) and return it as a 1D array.
avg=np.array([])
for i in range(len(scores)):
    avg=np.append(avg,np.sum(scores[i])/len(scores[i]))
print("Task3",avg) 

[[12 15 10 17]
 [14 13 12 18]
 [10 11  9 14]
 [16 17 18 19]]
Task1 [[13 12]
 [11  9]]
Task2 4 70
Task3 [13.5  14.25 11.   17.5 ]


In [5]:
#  4. Student Exam Results
#   You're working with the exam results of students across multiple subjects. The exam scores are stored in a 2D NumPy array, where each row represents a student and each column represents the scores in different subjects.
exam_scores = np.array([[85, 92, 78, 91],
                          [88, 74, 91, 85],
                          [78, 79, 82, 80],
                          [91, 84, 77, 90],
                          [80, 88, 84, 85]])
print(exam_scores)
#   Task:
#   - Extract the scores for the third student in all subjects.
print("Task1",exam_scores[2])
#   - Find the total score for the second subject (column 1) across all students.
print("Task2",np.sum(exam_scores[:,1]))
#   - Determine the average score of the first subject for the top 3 performing students in the last subject.
sum=0
top_scores=sorted(exam_scores[:,3],reverse=True)[0:3]
print(top_scores)
c=0
last=3
for i,v in np.ndenumerate(exam_scores[:,0]):
   if exam_scores[i][last] in top_scores:
       sum+=v
       print(v)
       c+=1
print("Avg",sum/c)

[[85 92 78 91]
 [88 74 91 85]
 [78 79 82 80]
 [91 84 77 90]
 [80 88 84 85]]
Task1 [78 79 82 80]
Task2 417
[np.int64(91), np.int64(90), np.int64(85)]
85
88
91
80
Avg 86.0


In [6]:
#  5. Climate Data Analysis
     
#   As part of a climate research project, you need to analyze temperature data across different regions and months. The data is stored in a 2D NumPy array, where each row represents a region and each column represents a month of the year.

   
temperatures = np.array([[30, 32, 31, 29, 28, 27, 26, 25, 24, 23, 22, 21],
                            [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
                            [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
                            [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])    
print(temperatures)
#   Task:
#   - Extract the temperatures of region 3 for the first six months.
print(temperatures[2,:6])
#   - Find the highest temperature in region 2 and identify the corresponding month.
mx=np.max(temperatures[1,:])
for i,v in np.ndenumerate(temperatures[1,:]):
    if v==mx:
        if i[0]==11:
            print("December")
#   - For regions 1 and 4, calculate the average temperature for the months of June, July, and August. 
r=temperatures[0::3,5:8]
print(r)
for i in range(len(r)):

    print(np.sum(r[i])/3)

[[30 32 31 29 28 27 26 25 24 23 22 21]
 [15 16 17 18 19 20 21 22 23 24 25 26]
 [10 11 12 13 14 15 16 17 18 19 20 21]
 [40 41 42 43 44 45 46 47 48 49 50 51]]
[10 11 12 13 14 15]
December
[[27 26 25]
 [45 46 47]]
26.0
46.0


In [7]:
#  6. Factory Production Analysis  
# A factory produces different types of products, 
# and the production count is stored in a 2D NumPy array,
# where each row represents a department, and each column represents a product type.

# python
production = np.array([[500, 600, 550, 580],
                       [450, 480, 500, 520],
                       [700, 750, 720, 740],
                       [550, 580, 600, 620]])

print(production)
#  Task:  
# - Extract the production count of department 3 for product types 2 and 3. 
print("Task1",production[2,1:3])
# - Find the total production count for product type 4 across all departments.  
print("Task2",production[:,3])
# - Identify which department has the highest total production count across all product types.
max=0
department=0
for i in range(len(production)):
    for j in range(len(production[i])):
        if production[i][j]>max:
            max=production[i][j]
            department=i
print("Department3",department+1)
        

[[500 600 550 580]
 [450 480 500 520]
 [700 750 720 740]
 [550 580 600 620]]
Task1 [750 720]
Task2 [580 520 740 620]
Department3 3


In [13]:
#  7. Employee Work Hours Analysis  
# A company tracks employee work hours in a 2D NumPy array, where each row represents an employee 
# and each column represents the hours worked per week over 4 weeks.

# python
work_hours = np.array([[40, 42, 38, 41],
                       [35, 36, 34, 38],
                       [45, 46, 44, 47],
                       [39, 40, 41, 42]])

print(work_hours)
#  Task:  
# - Extract the work hours of employees 2 and 4 for weeks 2 and 3.  
print("Task1",work_hours[1::2,1:3])
# - Calculate the total work hours for employee 1 across all weeks.  
print("Task2",np.sum(work_hours[0,:]))
# - Find the average work hours per week for all employees.

for i in range(len(work_hours)):
    sum=0
    for j in range(len(work_hours[i])):
        sum+=work_hours[j][i]
    print(f"Avg Week {i+1} is {sum/4}")

    print()

[[40 42 38 41]
 [35 36 34 38]
 [45 46 44 47]
 [39 40 41 42]]
Task1 [[36 34]
 [40 41]]
Task2 161
Avg Week 1 is 39.75

Avg Week 2 is 41.0

Avg Week 3 is 39.25

Avg Week 4 is 42.0



In [20]:
#  8. Sales Revenue Analysis  
# A retail store records its monthly revenue for different branches in a 2D NumPy array,
# where each row represents a branch and each column represents a month (January to June).

# python
revenue = np.array([[20000, 22000, 25000, 24000, 23000, 26000],
                    [18000, 19000, 20000, 21000, 22000, 23000],
                    [30000, 31000, 32000, 33000, 34000, 35000]])

print(revenue)
#  Task:  
# - Extract the revenue for branch 2 from March to June.  
print("Task1",revenue[1,2:])
# - Find the total revenue generated by branch 1.  
print("Task2",np.sum(revenue[0]))
# - Determine the highest revenue month for branch 3.
print("Task3",np.max(revenue[2]))

[[20000 22000 25000 24000 23000 26000]
 [18000 19000 20000 21000 22000 23000]
 [30000 31000 32000 33000 34000 35000]]
Task1 [20000 21000 22000 23000]
Task2 140000
Task3 35000


In [34]:
#  9. Hospital Patient Admissions  
# A hospital records the number of patients admitted each day in different wards using a 2D NumPy array, 
# where each row represents a ward and each column represents a day of the week (Monday-Sunday).

# python
admissions = np.array([[30, 25, 28, 32, 29, 31, 35],
                        [20, 18, 22, 24, 21, 23, 26],
                        [40, 38, 42, 45, 44, 47, 50]
])
print(admissions)
#  Task:  
# - Extract the admissions count for ward 3 on Wednesday and Thursday.  
print("Task1",admissions[2,2:4])
# - Find the total admissions for ward 1 during the week.  
print("Task2",np.sum(admissions[0]))
# - Identify which day had the highest total admissions across all wards.
mx=0
ad=0
for i,v in np.ndenumerate(admissions):
    if v>mx:
        mx=v
        ad=i[1]
if ad==0:
    print("Monday")
elif ad==1:
    print("Tuesday")
elif ad==6:
    print("Sunday",end=" ")
print(mx)

[[30 25 28 32 29 31 35]
 [20 18 22 24 21 23 26]
 [40 38 42 45 44 47 50]]
Task1 [42 45]
Task2 210
Sunday 50


In [38]:
#  10. E-commerce Order Processing  
# An e-commerce company tracks the number of orders processed per day across different warehouses in a 2D NumPy array,
# where each row represents a warehouse and each column represents a day of the week (Monday to Sunday).

# python
orders = np.array([[120, 150, 130, 140, 135, 160, 170],
                   [100, 110, 115, 120, 125, 130, 135],
                   [200, 210, 190, 220, 230, 240, 250]])

print(orders)
#  Task:  
# - Retrieve the order counts from warehouse 2 for Monday and Thursday. 
print("Task1",orders[1,0:4])
# - Find the total orders processed by warehouse 3 during the week. 
print("Task2",np.sum(orders[2]))
# - Determine which warehouse had the highest total order count.
mx=0
w=0
for i in range(len(orders)):
    if np.sum(orders[i])>mx:
        mx=np.sum(orders[i])
        w=i+1
print("Task3",w)

[[120 150 130 140 135 160 170]
 [100 110 115 120 125 130 135]
 [200 210 190 220 230 240 250]]
[100 110 115 120]
1540
3


In [45]:
#  11. Airline Passenger Traffic Analysis  
# An airline tracks the number of passengers traveling each month in a 2D NumPy array,
# where each row represents a flight route and each column represents a month from January to June.

# python
passengers = np.array([[10000, 12000, 14000, 13000, 12500, 15000],
                       [8000, 9000, 9500, 10000, 10500, 11000],
                       [15000, 16000, 15500, 17000, 18000, 19000]])
print(passengers)


#  Task:  
# - Extract the passenger count for route 2 from March to June.  
print("Task1",np.sum(passengers[1,2:]))
# - Find the total passengers for route 1 over the six months. 
print("Task2",np.sum(passengers[0]))
# - Identify the month with the highest total passenger count across all routes.
mx=0
month=0
for i,v in np.ndenumerate(passengers):
    if v>mx:
        mx=v
        month=i[1]
if month==5:
    print("June")
# print(month)

[[10000 12000 14000 13000 12500 15000]
 [ 8000  9000  9500 10000 10500 11000]
 [15000 16000 15500 17000 18000 19000]]
Task1 41000
Task2 76500
June


In [54]:
#  12. Agricultural Crop Yield Analysis  
# A farm tracks the crop yield (in tons) per month for different fields using a 2D NumPy array, 
# where each row represents a field and each column represents a month from January to May.

# python
crop_yield = np.array([[50, 55, 53, 60, 62],
                        [40, 42, 45, 47, 50],
                        [70, 75, 78, 80, 85]])

print(crop_yield)
#  Task:  
# - Retrieve the crop yield for field 1 in March and April. 
print("Task1",np.sum(crop_yield[0,2:4]))
# - Calculate the total crop yield for field 3 over five months.  
print("Task2",np.sum(crop_yield[2,:]))
# - Find the average crop yield per month across all fields
for i in range(len(crop_yield)):
    sum=0
    for j in range(3):
        sum+=crop_yield[j][i]
    print("Avg",sum/3)
        
      

[[50 55 53 60 62]
 [40 42 45 47 50]
 [70 75 78 80 85]]
Task1 113
Task2 388
Avg 53.333333333333336
Avg 57.333333333333336
Avg 58.666666666666664
