In [1]:
import numpy as np

In [4]:
# 1. 2D Array Creation
#    Create a 2D NumPy array of shape (3, 4) with values ranging from 1 to 12.
print(np.array(range(1,13)).reshape(3,4))
np.arange(1,13).reshape(3,4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# 2. 3D Array Creation
#    Create a 3D NumPy array of shape (2, 3, 4) with sequential numbers starting from 1.
np.arange(1,25).reshape(2,3,4)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [7]:
# 3. 2D Slicing
#    Given the following array:

#    A = [[1, 2, 3, 4],
#         [5, 6, 7, 8],
#         [9, 10, 11, 12]]

#    Extract a subarray containing the last two rows and the last two columns.
arr=np.array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]])
arr
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [9]:
# 4. 3D Slicing
#    Given the following 3D array:

#    A = [[[1, 2, 3, 4],
#          [5, 6, 7, 8],
#          [9, 10, 11, 12]],

#         [[13, 14, 15, 16],
#          [17, 18, 19, 20],
#          [21, 22, 23, 24]]]

#    Extract all elements from the second matrix (i.e., elements from index 1).
arr=np.array([[[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
arr
arr[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [11]:
# 5. Iterating Over a 2D Array
#    Given the array:

#    A = [[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]]

#    Print all elements row-wise.
arr=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
l=arr.shape
for i in range(l[0]):
  print(arr[i])

[1 2 3]
[4 5 6]
[7 8 9]


In [15]:
# 6. Iterating Over a 3D Array
#    Given a 3D NumPy array of shape (2, 3, 3), iterate through all its elements one by one.
arr=np.arange(1,19).reshape(2,3,3)
for i in np.nditer(arr):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [19]:
# 7. Update Specific Value in a 2D Array
#    Given the array:

#    A = [[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]]

#    Change the value at index (1,1) to 99.
arr=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
print(arr)
arr[1,1]=99
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [20]:
# 8. Update Entire Row in a 2D Array
#    Given the array:

#    A = [[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]]

#    Replace the second row with [10, 11, 12].
arr=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]] )
print(arr)
arr[1]=[10,11,12]
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [23]:
# 9. Insert a Row in a 2D Array
#    Given the array:

#    A = [[1, 2, 3],
#         [4, 5, 6]]

  #  Insert a new row [7, 8, 9] at index 1.
arr=np.array([[1, 2, 3],
        [4, 5, 6]])
print(np.insert(arr,1,[7,8,9],axis=0))
arr


[[1 2 3]
 [7 8 9]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# 10. Insert a Column in a 2D Array
#    Given the array:

#    A = [[1, 2],
#         [3, 4],
#         [5, 6]]

#    Insert a new column [7, 8, 9] at index 1.
arr=np.array([[1, 2],
        [3, 4],
        [5, 6]])
arr
np.insert(arr,1,[7,8,9],axis=1)

array([[1, 7, 2],
       [3, 8, 4],
       [5, 9, 6]])

In [29]:
# 11. Delete a Row in a 2D Array
#    Given the array:

#    A = [[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]]

#    Delete the second row.
arr=np.array( [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

print(np.delete(arr,1,axis=0))
arr

[[1 2 3]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# 12. Delete a Column in a 2D Array
#    Given the array:

#    A = [[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]]

#    Delete the last column.
arr=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
print(arr)
np.delete(arr,2,axis=1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [40]:
# 13. Appending a Row to a 2D Array
  #  Given the array:

  #  A = [[1, 2, 3],
  #       [4, 5, 6]]

  #  Append the row [7, 8, 9] to the array.
arr=np.array([[1, 2, 3],
        [4, 5, 6]])
print(arr)
np.append(arr,[[7,8,9]],axis=0)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# 14. Appending a 3D Array
#    Given two 3D arrays:

#    A = [[[1, 2], [3, 4]],
#         [[5, 6], [7, 8]]]

#    B = [[[9, 10], [11, 12]]]

#    Append B to A along axis 0.

arr1=np.array([[[1, 2], [3, 4]],
        [[5, 6], [7, 8]]])
arr2=np.array([[[9, 10], [11, 12]]])
print(arr1)
print(arr2)
np.append(arr1,arr2,axis=0)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 9 10]
  [11 12]]]


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [46]:
# 15. Find Even Numbers in a 2D Array
#     Given the array:

#          A = [[10, 15, 20],
#      	     [25, 30, 35],
#              [40, 45, 50]]

# Extract all even numbers.
arr=np.array([[10, 15, 20],
     	     [25, 30, 35],
             [40, 45, 50]])
print(arr)
for i in np.nditer(arr):
  if i%2==0:
   print(i,end=" ")

[[10 15 20]
 [25 30 35]
 [40 45 50]]
10 20 30 40 50 