In [2]:
import numpy as np

1. Extract alternate elements from each row in a 2D NumPy array.  
   Input:  
   
   [[10, 20, 30, 40],  
    [50, 60, 70, 80],  
    [90, 100, 110, 120]]  
   
   Output:  
   
   [[10, 30],  
    [50, 70],  
    [90, 110]]  
   

2. Extract the first and last column from a 3D NumPy array.  
   Input:  
   
   [[[1, 2, 3], [4, 5, 6]],  
    [[7, 8, 9], [10, 11, 12]]]  
   
   Output:  
   
   [[[1, 3],  
     [4, 6]],  
    [[7, 9],  
     [10, 12]]]  
   

3. Select the second row from each 2D array in a 3D NumPy array.  
   Input:  
   
   [[[5, 6, 7], [8, 9, 10]],  
    [[15, 16, 17], [18, 19, 20]],  
    [[25, 26, 27], [28, 29, 30]]]  
   
   Output:  
   
   [[8, 9, 10],  
    [18, 19, 20],  
    [28, 29, 30]]  
   

4. Extract elements from even rows and odd columns in a 2D NumPy array.  
   Input:  
   
   [[1, 2, 3, 4],  
    [5, 6, 7, 8],  
    [9, 10, 11, 12],  
    [13, 14, 15, 16]]  
   
   Output:  
   
   [[2, 4],  
    [10, 12]]  
   

5. Extract diagonal elements from each matrix in a 3D array.  
   Input:  
   
   [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]  
   
   Output:  
   
   [[1, 5, 9],  
    [10, 14, 18]]  
   

6. Reverse the last two columns in a 2D NumPy array.  
   Input:  
   
   [[10, 20, 30, 40],  
    [50, 60, 70, 80]]  
   
   Output:  
   
   [[10, 20, 40, 30],  
    [50, 60, 80, 70]]  
   

7. Extract elements from the first and last row of a 2D NumPy array.  
   Input:  
   
   [[1, 2, 3],  
    [4, 5, 6],  
    [7, 8, 9]]  
   
   Output:  
   
   [[1, 2, 3],  
    [7, 8, 9]]  
   

8. Extract every second element from a 3D NumPy array.  
   Input:  
   
   [[[10, 20, 30], [40, 50, 60]],  
    [[70, 80, 90], [100, 110, 120]]]  
   
   Output:  
   
   [[[10, 30],  
     [40, 60]],  
    [[70, 90],  
     [100, 120]]]  
   

9. Extract elements from the second column of each 2D slice in a 3D array.  
   Input:  
   
   [[[1, 2, 3], [4, 5, 6]],  
    [[7, 8, 9], [10, 11, 12]]]  
   
   Output:  
   
   [[2, 5],  
    [8, 11]]  
   

10. Swap the first and last row of a 2D NumPy array.  
   Input:  
   
   [[1, 2, 3],  
    [4, 5, 6],  
    [7, 8, 9]]  
   
   Output:  
   
   [[7, 8, 9],  
    [4, 5, 6],  
    [1, 2, 3]]  
   

11. Extract elements where the row index is even and the column index is odd.  
   Input:  
   
   [[10, 11, 12, 13],  
    [14, 15, 16, 17],  
    [18, 19, 20, 21],  
    [22, 23, 24, 25]]  
   
   Output:  
   
   [[11, 13],  
    [19, 21]]  
   

12. Extract the last two elements of each row in a 2D NumPy array.  
   Input:  
   
   [[1, 2, 3, 4],  
    [5, 6, 7, 8],  
    [9, 10, 11, 12]]  
   
   Output:  
   
   [[3, 4],  
    [7, 8],  
    [11, 12]]  
   

13. Extract the first and last row of each 2D matrix in a 3D NumPy array.  
   Input:  
   
   [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]  
   
   Output:  
   
   [[[1, 2, 3],  
     [7, 8, 9]],  
    [[10, 11, 12],  
     [16, 17, 18]]]  
   

14. Extract elements from all 3D matrices where both row and column indices are odd.  
   Input:  
   
   [[[1, 2, 3, 4],  
     [5, 6, 7, 8],  
     [9, 10, 11, 12],  
     [13, 14, 15, 16]]]  
   
   Output:  
   
   [[6, 8],  
    [14, 16]]  
   

15. Extract elements from the first column and last row in each 2D matrix of a 3D array.  
   Input:  
   
   [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]  
   
   Output:  
   
   [[1, 7],  
    [10, 16]]  
   

In [3]:
# 1.# Extract alternate elements from each row in a 2D NumPy array.
# Input:
# Output:

# [[10, 30],
# [50, 70],
# [90, 110]]

arr=np.array([[10, 20, 30, 40],
[50, 60, 70, 80],
[90, 100, 110, 120]])
arr[::,::2]



array([[ 10,  30],
       [ 50,  70],
       [ 90, 110]])

In [4]:
# 2. Extract the first and last column from a 3D NumPy array.
#    Input:

#    [[[1, 2, 3], [4, 5, 6]],
#     [[7, 8, 9], [10, 11, 12]]]

#    Output:

#    [[[1, 3],
#      [4, 6]],
#     [[7, 9],
#      [10, 12]]]

arr=np.array([[[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]])
print(arr)
arr[:,::,::2]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  3],
        [ 4,  6]],

       [[ 7,  9],
        [10, 12]]])

In [5]:
# 3. Select the second row from each 2D array in a 3D NumPy array.
#    Input:



#    Output:

#    [[8, 9, 10],
#     [18, 19, 20],
#     [28, 29, 30]]
arr=np.array([[[5, 6, 7], [8, 9, 10]],
    [[15, 16, 17], [18, 19, 20]],
    [[25, 26, 27], [28, 29, 30]]]  )
print(arr)
arr[:,1,:]

[[[ 5  6  7]
  [ 8  9 10]]

 [[15 16 17]
  [18 19 20]]

 [[25 26 27]
  [28 29 30]]]


array([[ 8,  9, 10],
       [18, 19, 20],
       [28, 29, 30]])

In [6]:
# 4. Extract elements from even rows and odd columns in a 2D NumPy array.
#    Input:

#    [[1, 2, 3, 4],
#     [5, 6, 7, 8],
#     [9, 10, 11, 12],
#     [13, 14, 15, 16]]

#    Output:

#    [[2, 4],
#     [10, 12]]
arr=np.array([[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]])
print(arr)
arr[::2,1::2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 2,  4],
       [10, 12]])

In [22]:
# 5. Extract diagonal elements from each matrix in a 3D array.
#    Input:

arr=np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]  )

#    Output:

#    [[1, 5, 9],
#     [10, 14, 18]]
print(arr)
for i in arr:
  print(np.diagonal(i))


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[1 5 9]
[10 14 18]


In [25]:
# 6. Reverse the last two columns in a 2D NumPy array.
#    Input:

arr=np.array([[10, 20, 30, 40],
    [50, 60, 70, 80]] )
print(arr)


#    Output:

#    [[10, 20, 40, 30],
#     [50, 60, 80, 70]]

arr[:,-2:]=arr[:,-1:-3:-1]
arr

[[10 20 30 40]
 [50 60 70 80]]


array([[10, 20, 40, 30],
       [50, 60, 80, 70]])

In [9]:
# 7. Extract elements from the first and last row of a 2D NumPy array.
#    Input:

arr=np.array([[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

  #  Output:

  #  [[1, 2, 3],
  #   [7, 8, 9]]
print(arr)
arr[::2,:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [7, 8, 9]])

In [10]:
# 8. Extract every second element from a 3D NumPy array.
#    Input:

arr=np.array([[[10, 20, 30], [40, 50, 60]],
    [[70, 80, 90], [100, 110, 120]]]  )
print(arr)
arr[:,:,::2]

  #  Output:

  #  [[[10, 30],
  #    [40, 60]],
  #   [[70, 90],
  #    [100, 120]]]

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


array([[[ 10,  30],
        [ 40,  60]],

       [[ 70,  90],
        [100, 120]]])

In [11]:
# 9. Extract elements from the second column of each 2D slice in a 3D array.
#    Input:

arr=np.array([[[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]])

#    Output:

#    [[2, 5],
#     [8, 11]]
print(arr)
arr[:,:,1]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[ 2,  5],
       [ 8, 11]])

In [13]:
# 10. Swap the first and last row of a 2D NumPy array.
#    Input:

arr=np.array([[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

  #  Output:

  #  [[7, 8, 9],
  #   [4, 5, 6],
  #   [1, 2, 3]]

temp=arr[0,:]
arr[0,:]=arr[2,:]
arr[2,:]=temp
arr

array([[7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# 11. Extract elements where the row index is even and the column index is odd.
#    Input:

arr=np.array([[10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21],
    [22, 23, 24, 25]]  )

  #  Output:

  #  [[11, 13],
  #   [19, 21]]
arr[::2,1::2]

array([[11, 13],
       [19, 21]])

In [15]:
# 12. Extract the last two elements of each row in a 2D NumPy array.
  #  Input:

arr=np.array([[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]] )

  #  Output:

  #  [[3, 4],
  #   [7, 8],
  #   [11, 12]]
arr[:,-2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [18]:
# 13. Extract the first and last row of each 2D matrix in a 3D NumPy array.
#    Input:
arr=np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]] )
print(arr)

  #  Output:

  #  [[[1, 2, 3],
  #    [7, 8, 9]],
  #   [[10, 11, 12],
  #    [16, 17, 18]]]
arr[:,::2,:]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [16, 17, 18]]])

In [21]:
# 15. Extract elements from the first column and last row in each 2D matrix of a 3D array.
#    Input:

arr=np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]  )

  #  Output:

  #  [[1, 7],
  #   [10, 16]]
print(arr)
arr[:,::2,0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[ 1,  7],
       [10, 16]])